name: aziz_graphics_app
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1  # Version number and build number

environment:
  sdk: ">=2.18.0 <3.0.0"  # Specifies the Flutter SDK range compatible with Flutter 2.x

dependencies:
  flutter:
    sdk: flutter  # Flutter SDK dependency
  webview_flutter: ^3.0.0     # Older, compatible version of the webview_flutter plugin
  path_provider: ^2.0.2       # Stable version of path_provider
  file_picker: ^5.0.0         # Older version of file_picker plugin (v1 embedding compatible)
  cupertino_icons: ^1.0.8     # Cupertino icons package for iOS-style icons

dev_dependencies:
  flutter_test:
    sdk: flutter  # Default testing dependency for Flutter
  flutter_lints: ^2.0.0      # Lint package to help with code quality and style

flutter:
  uses-material-design: true  # Enables the use of material design in your app
